// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.se;

import com.sut.se.Nameee;

privileged aspect Nameee_Roo_JavaBean {
    
    public String Nameee.getNameee() {
        return this.nameee;
    }
    
    public void Nameee.setNameee(String nameee) {
        this.nameee = nameee;
    }
    
}
